"""Initial migration

Revision ID: 0a68f7758fce
Revises: 28e7924d8e79
Create Date: 2025-01-04 10:21:26.337496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a68f7758fce'
down_revision: Union[str, None] = '28e7924d8e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.drop_constraint('reports_user_id_fkey', 'reports', type_='foreignkey')
    op.drop_column('reports', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('reports_user_id_fkey', 'reports', 'users', ['user_id'], ['id'])
    op.drop_column('reports', 'telegram_id')
    # ### end Alembic commands ###
