"""Added users and reports tables

Revision ID: 28e7924d8e79
Revises: 66d6f7903add
Create Date: 2025-01-03 17:49:27.527028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e7924d8e79'
down_revision: Union[str, None] = '66d6f7903add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('type', sa.String(), nullable=False))
    op.add_column('reports', sa.Column('status', sa.String(), nullable=False))
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('reports', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'status')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'language')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.alter_column('reports', 'amount',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('reports', 'updated_at')
    op.drop_column('reports', 'status')
    op.drop_column('reports', 'type')
    # ### end Alembic commands ###
