"""Added users and reports tables

Revision ID: 4bef7c9f8dc1
Revises: 28e7924d8e79
Create Date: 2025-01-04 10:42:47.316007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bef7c9f8dc1'
down_revision: Union[str, None] = '28e7924d8e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
